"""added item table

Revision ID: 765806996f59
Revises: d3e380f128e4
Create Date: 2024-04-03 00:42:51.283979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765806996f59'
down_revision = 'd3e380f128e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=11), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
