"""added status to group

Revision ID: a2babf46da63
Revises: 765806996f59
Create Date: 2024-04-03 01:12:44.263787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2babf46da63'
down_revision = '765806996f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('status', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'status')
    # ### end Alembic commands ###
